services:
  - type: web
    name: lead-management-backend
    plan: free
    region: oregon
    repo: https://github.com/HON-AIM/Leads-Management-Saas
    branch: main
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 10000