export const ROUTES = {
  LOGIN: '/login',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  DASHBOARD: '/dashboard',
  LEADS: '/leads',
  BUYERS: '/buyers',
  CAMPAIGNS: '/campaigns',
  DELIVERY: '/delivery',
  REPORTS: '/reports',
  SETTINGS: '/settings',
  TEAM: '/team',
  SUPPLIERS: '/suppliers',
} as const

export const QUERY_KEYS = {
  STATS: ['stats'],
  LEADS: ['leads'],
  BUYERS: ['buyers'],
  BUYER_DISTRIBUTION: ['buyer-distribution'],
  CAMPAIGNS: ['campaigns'],
  DELIVERY_LOGS: ['delivery-logs'],
  DELIVERY_STATS: ['delivery-stats'],
  DELIVERY_TRENDS: ['delivery-trends'],
  SUPPLIERS: ['suppliers'],
  CLIENTS: ['clients'],
  SESSIONS: ['sessions'],
  SETTINGS: ['settings'],
  API_KEY: ['api-key'],
  REPORTS: ['reports'],
} as const
